[package]
name = "atosl"
version = "0.1.4"
edition = "2021"
description = "atosl by rust"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
clap = { version = "3.0.0", features = ["derive"] }
gimli = "0.26.1"
memmap = "0.7.0"
object = "0.28.1"
