name: Publish
on:
  push:
#    branches:
#      - main  # 更改为你的主分支
    tags:
      - 'v*'
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build for AMD64
        run: cargo build --release --target=x86_64-unknown-linux-gnu
      - name: Move binaries
        run: |
          mkdir -p .bin
          ls target/release/
          mv target/release/atosl .bin/atosl-linux-amd64-${{ github.ref }}
      - uses: svenstaro/upload-release-action@2.4.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: .bin/atosl-linux-amd64-${{ github.ref }}
          asset_name: atosl-linux-amd64-${{ github.ref }}
#          tag: v0.1.0-${{ steps.timestamp.outputs.timestamp }}
          overwrite: true
          body: "This is my release text"
