name: Publish
on:
  push:
    branches:
      - main  # 更改为你的主分支
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - name: Build
#        run: cargo build --release
      - name: Build for M1
        run: |
          mkdir -p target/m1
          CARGO_TARGET_DIR=target/m1 cargo build --release --target=aarch64-apple-darwin
      - name: Build for AMD64
        run: |
          mkdir -p target/amd64
          CARGO_TARGET_DIR=target/amd64 cargo build --release --target=x86_64-unknown-linux-gnu
      - name: Move binaries
        run: |
          mkdir -p .bin
          ls target/m1/release/
          ls target/amd64/release/
          mv target/m1/release/atosl .bin/atosl-m1
          mv target/amd64/release/atosl .bin/atosl-amd
#          mv -v target/release/* .bin/
      - name: Get Current Timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%s)"
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@2.4.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: .bin/*
#          asset_name: atosl-amd
          tag: v0.1.0-${{ steps.timestamp.outputs.timestamp }}
          overwrite: true
          body: "This is my release text"
